style: IDE0008
philips-software/roslyn-analyzers pull request #466
Opened 2023-02-21 12:43 UTC by bcollamore

2023-02-21 19:21 UTC, ynsehoornenborg requested changes
Let's enable `csharp_style_var_for_built_in_types` also, as we're actually removing many `var` statement with this PR

2023-02-21 19:22 UTC, ynsehoornenborg requested changes
Lat's use `csharp_style_var_for_built_in_types` also, as with this configuration we're actually removing many `var` keywords.

2023-02-21 21:40 UTC, bcollamore commented on Philips.CodeAnalysis.MaintainabilityAnalyzers/Documentation/DocumentThrownExceptionsCodeFixProvider.cs
> +			Microsoft.CodeAnalysis.CSharp.Syntax.DocumentationCommentTriviaSyntax newComment = docHelper.CreateDocumentation();
done

2023-02-21 21:40 UTC, bcollamore commented on Philips.CodeAnalysis.MaintainabilityAnalyzers/Documentation/DocumentThrownExceptionsCodeFixProvider.cs
> +			Microsoft.CodeAnalysis.Text.TextSpan diagnosticSpan = diagnostic.Location.SourceSpan;
done

2023-02-22 03:09 UTC, bcollamore commented
> Lat's use `csharp_style_var_for_built_in_types` also, as with this configuration we're actually removing many `var` keywords.

done

2023-02-22 19:23 UTC, ynsehoornenborg approved these changes

2023-02-22 19:38 UTC, merged