docs: 439 enable cs1591
philips-software/roslyn-analyzers pull request #516
Opened 2023-03-07 08:44 UTC by ynsehoornenborg

2023-03-07 23:44 UTC, bcollamore requested changes

2023-03-07 23:44 UTC, bcollamore commented on Documentation/Diagnostics/PH2001.md
> +Note: Creating useful comments for every member can be a large effort and if you named your members correctly, their name specifies the purpose already. In these cases XML documentation might not add
interference

2023-03-08 15:24 UTC, ynsehoornenborg commented on Documentation/Diagnostics/PH2001.md
> +Note: Creating useful comments for every member can be a large effort and if you named your members correctly, their name specifies the purpose already. In these cases XML documentation might not add
Corrected in both MD files

2023-03-08 15:56 UTC, bcollamore approved these changes

2023-03-08 16:01 UTC, merged