fix: Diagnostic on empty regions
philips-software/roslyn-analyzers pull request #715
Opened 2023-11-15 20:25 UTC by ynsehoornenborg

Empty is defined here, as no `TypeDeclaration` or `MemberDeclaration` inside the region.

Please note that regions inside methods are allowed now.

2023-11-17 08:47 UTC, bcollamore requested changes

2023-11-28 13:17 UTC, ynsehoornenborg commented on Documentation/Diagnostics/PH2141.md
> +| Diagnostic ID | PH2140 |
Corrected

2023-11-28 13:18 UTC, ynsehoornenborg commented on Documentation/Diagnostics/PH2141.md
> +| CodeFix  | No |
typo

2023-11-28 13:18 UTC, ynsehoornenborg commented on Documentation/Diagnostics/PH2141.md
> +Avoid writing rfegions with no code inside.
typo

2023-11-28 18:58 UTC, ynsehoornenborg commented on Documentation/Diagnostics/PH2141.md
> +| CodeFix  | No |
I guess we should add one here...

2025-03-19 15:48 UTC, bcollamore commented on Documentation/Diagnostics/PH2141.md
> +| CodeFix  | No |
Created a separate issue for this.

2025-03-19 16:49 UTC, bcollamore approved these changes

2025-03-19 16:52 UTC, merged