feat: New Analyzer to avoid cast to `string`
philips-software/roslyn-analyzers pull request #716
Opened 2023-11-16 14:31 UTC by ynsehoornenborg

Implement, test and doc

2023-11-17 08:50 UTC, bcollamore requested changes

2023-11-17 08:50 UTC, bcollamore commented on Documentation/Diagnostics/PH2142.md
> +# PH2140: Avoid Cast to String
2140

2023-11-17 08:50 UTC, bcollamore commented on Documentation/Diagnostics/PH2142.md
> +Avoid casting to int, use `object.ToString()` or a serialization solution instead.
int?

2023-11-28 13:16 UTC, ynsehoornenborg commented on Documentation/Diagnostics/PH2142.md
> +Avoid casting to int, use `object.ToString()` or a serialization solution instead.
oops, typo

2023-11-28 13:17 UTC, ynsehoornenborg commented on Documentation/Diagnostics/PH2142.md
> +# PH2140: Avoid Cast to String
Corrected

2023-11-28 19:07 UTC, merged